### ISSUE TITLE
Issues running in docker-compose

### ISSUE THREAD

**Issue by prabinv** [apache/casbin-server#94]
Hi All, I'm trying to run casbin-server in docker-compose along with a postgresql database based on the [instructions here](https://github.com/casbin/casbin-server#docker-way). I'm mounting a volume with the connection config json file and the model configuration files in the casbin-server container and setting up the environment variable ( to point to the config file. The casbin-server container logs says that it is Listening on 50051. I have mapped the local port 5005 to the port 50051 of the container. But I'm getting the error `ERR_INVALID_HTTP_RESPONSE` when trying to load the URL. I verified that I can connect to the database from the casbin-server container. I also tried running curl inside the casbin-server container on the port 50051, but I get a `Connection reset by peer` error.

What might be the issue here? Can you provide some guidance on the running casbin-server in docker compose?

I'm on a Macbook running macOS Ventura 13.1. Here is the docker-compose file I'm using:

```yaml
services:
  auth-service:
    image: casbin/casbin-server:v1.9.0
    container_name: casbin-server
    ports:
      - 5005:50051
    volumes:
      - ./config:/config
      - ./data/model:/model
    environment:
      - DB_DRIVER=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=auth
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - CONNECTION_CONFIG_PATH=/config/connection_config.json
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:12.2
    container_name: casbin_db
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "auth", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
```

The connection_config.json file is given below:
```json
{
  "driver": "postgres",
  "connection": "host=db port=5432 user=postgres dbname=auth password=postgres",
  "enforcer": "/model/model.conf",
  "dbSpecified" : true
}
```
